2024-12-08 14:01:31,046 - ModelTrainer - ERROR - Error in xgboost training: name 'CustomConformityScore' is not defined
2024-12-08 14:01:31,048 - ModelTrainer - ERROR - Traceback (most recent call last):
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 448, in train_model_with_mapie
    conformity_score = CustomConformityScore(
                       ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'CustomConformityScore' is not defined

2024-12-08 14:01:31,048 - ModelTrainer - ERROR - Error training XGBoost: name 'CustomConformityScore' is not defined
2024-12-08 14:01:31,050 - ModelTrainer - ERROR - Traceback (most recent call last):
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 753, in train_models
    self.train_model_with_mapie('xgboost', xgboost_best_params)
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 448, in train_model_with_mapie
    conformity_score = CustomConformityScore(
                       ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'CustomConformityScore' is not defined

2024-12-08 14:01:31,051 - ModelTrainer - ERROR - Error in model training pipeline
2024-12-08 14:01:31,051 - ModelTrainer - ERROR - Traceback (most recent call last):
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 753, in train_models
    self.train_model_with_mapie('xgboost', xgboost_best_params)
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 448, in train_model_with_mapie
    conformity_score = CustomConformityScore(
                       ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'CustomConformityScore' is not defined

