2024-12-08 04:52:13,627 - ModelTrainer - ERROR - Error in XGBoost trial 6: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,628 - ModelTrainer - ERROR - Error in XGBoost trial 9: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,629 - ModelTrainer - ERROR - Error in XGBoost trial 1: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,629 - ModelTrainer - ERROR - Error in XGBoost trial 3: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,646 - ModelTrainer - ERROR - Error in XGBoost trial 10: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,646 - ModelTrainer - ERROR - Error in XGBoost trial 4: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,648 - ModelTrainer - ERROR - Error in XGBoost trial 2: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,648 - ModelTrainer - ERROR - Error in XGBoost trial 7: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,649 - ModelTrainer - ERROR - Error in XGBoost trial 0: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,672 - ModelTrainer - ERROR - Error in XGBoost trial 5: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,682 - ModelTrainer - ERROR - Error in XGBoost trial 12: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,683 - ModelTrainer - ERROR - Error in XGBoost trial 13: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,685 - ModelTrainer - ERROR - Error in XGBoost trial 8: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,685 - ModelTrainer - ERROR - Error in XGBoost trial 11: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,721 - ModelTrainer - ERROR - Error in XGBoost trial 14: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,755 - ModelTrainer - ERROR - Error in XGBoost trial 15: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,763 - ModelTrainer - ERROR - Error in XGBoost trial 16: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,788 - ModelTrainer - ERROR - Error in XGBoost trial 17: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,812 - ModelTrainer - ERROR - Error in XGBoost trial 18: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,819 - ModelTrainer - ERROR - Error in XGBoost trial 19: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,847 - ModelTrainer - ERROR - Error in XGBoost trial 20: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,922 - ModelTrainer - ERROR - Error in XGBoost trial 22: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,927 - ModelTrainer - ERROR - Error in XGBoost trial 21: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,933 - ModelTrainer - ERROR - Error in XGBoost trial 23: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,941 - ModelTrainer - ERROR - Error in XGBoost trial 24: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:13,982 - ModelTrainer - ERROR - Error in XGBoost trial 25: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,006 - ModelTrainer - ERROR - Error in XGBoost trial 26: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,016 - ModelTrainer - ERROR - Error in XGBoost trial 27: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,160 - ModelTrainer - ERROR - Error in XGBoost trial 30: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,162 - ModelTrainer - ERROR - Error in XGBoost trial 28: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,190 - ModelTrainer - ERROR - Error in XGBoost trial 29: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,228 - ModelTrainer - ERROR - Error in XGBoost trial 31: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,244 - ModelTrainer - ERROR - Error in XGBoost trial 32: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,363 - ModelTrainer - ERROR - Error in XGBoost trial 33: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,369 - ModelTrainer - ERROR - Error in XGBoost trial 34: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,397 - ModelTrainer - ERROR - Error in XGBoost trial 35: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,487 - ModelTrainer - ERROR - Error in XGBoost trial 37: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,512 - ModelTrainer - ERROR - Error in XGBoost trial 36: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,575 - ModelTrainer - ERROR - Error in XGBoost trial 38: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,594 - ModelTrainer - ERROR - Error in XGBoost trial 39: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,615 - ModelTrainer - ERROR - Error in XGBoost trial 40: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,642 - ModelTrainer - ERROR - Error in XGBoost trial 41: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,687 - ModelTrainer - ERROR - Error in XGBoost trial 43: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,709 - ModelTrainer - ERROR - Error in XGBoost trial 44: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,712 - ModelTrainer - ERROR - Error in XGBoost trial 42: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,746 - ModelTrainer - ERROR - Error in XGBoost trial 45: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,780 - ModelTrainer - ERROR - Error in XGBoost trial 47: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,807 - ModelTrainer - ERROR - Error in XGBoost trial 46: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,816 - ModelTrainer - ERROR - Error in XGBoost trial 48: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,827 - ModelTrainer - ERROR - Error in XGBoost trial 49: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,890 - ModelTrainer - ERROR - Error in XGBoost trial 50: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,929 - ModelTrainer - ERROR - Error in XGBoost trial 51: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,966 - ModelTrainer - ERROR - Error in XGBoost trial 52: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:14,972 - ModelTrainer - ERROR - Error in XGBoost trial 53: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,016 - ModelTrainer - ERROR - Error in XGBoost trial 55: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,031 - ModelTrainer - ERROR - Error in XGBoost trial 54: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,083 - ModelTrainer - ERROR - Error in XGBoost trial 56: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,105 - ModelTrainer - ERROR - Error in XGBoost trial 57: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,134 - ModelTrainer - ERROR - Error in XGBoost trial 58: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,166 - ModelTrainer - ERROR - Error in XGBoost trial 60: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,190 - ModelTrainer - ERROR - Error in XGBoost trial 59: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,235 - ModelTrainer - ERROR - Error in XGBoost trial 62: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,235 - ModelTrainer - ERROR - Error in XGBoost trial 63: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,263 - ModelTrainer - ERROR - Error in XGBoost trial 61: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,281 - ModelTrainer - ERROR - Error in XGBoost trial 64: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,308 - ModelTrainer - ERROR - Error in XGBoost trial 65: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,359 - ModelTrainer - ERROR - Error in XGBoost trial 66: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,420 - ModelTrainer - ERROR - Error in XGBoost trial 68: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,427 - ModelTrainer - ERROR - Error in XGBoost trial 67: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,473 - ModelTrainer - ERROR - Error in XGBoost trial 69: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,509 - ModelTrainer - ERROR - Error in XGBoost trial 70: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,537 - ModelTrainer - ERROR - Error in XGBoost trial 71: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,552 - ModelTrainer - ERROR - Error in XGBoost trial 72: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,578 - ModelTrainer - ERROR - Error in XGBoost trial 73: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,614 - ModelTrainer - ERROR - Error in XGBoost trial 74: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,663 - ModelTrainer - ERROR - Error in XGBoost trial 75: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,693 - ModelTrainer - ERROR - Error in XGBoost trial 76: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,714 - ModelTrainer - ERROR - Error in XGBoost trial 77: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,740 - ModelTrainer - ERROR - Error in XGBoost trial 78: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,771 - ModelTrainer - ERROR - Error in XGBoost trial 79: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,781 - ModelTrainer - ERROR - Error in XGBoost trial 80: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,827 - ModelTrainer - ERROR - Error in XGBoost trial 81: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,865 - ModelTrainer - ERROR - Error in XGBoost trial 82: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,886 - ModelTrainer - ERROR - Error in XGBoost trial 83: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,906 - ModelTrainer - ERROR - Error in XGBoost trial 84: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,976 - ModelTrainer - ERROR - Error in XGBoost trial 87: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:15,982 - ModelTrainer - ERROR - Error in XGBoost trial 85: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,026 - ModelTrainer - ERROR - Error in XGBoost trial 86: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,038 - ModelTrainer - ERROR - Error in XGBoost trial 89: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,091 - ModelTrainer - ERROR - Error in XGBoost trial 88: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,099 - ModelTrainer - ERROR - Error in XGBoost trial 90: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,136 - ModelTrainer - ERROR - Error in XGBoost trial 91: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,183 - ModelTrainer - ERROR - Error in XGBoost trial 92: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,200 - ModelTrainer - ERROR - Error in XGBoost trial 93: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,205 - ModelTrainer - ERROR - Error in XGBoost trial 95: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,214 - ModelTrainer - ERROR - Error in XGBoost trial 94: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,238 - ModelTrainer - ERROR - Error in XGBoost trial 98: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,245 - ModelTrainer - ERROR - Error in XGBoost trial 97: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,250 - ModelTrainer - ERROR - Error in XGBoost trial 96: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,297 - ModelTrainer - ERROR - Error in XGBoost trial 99: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,405 - ModelTrainer - ERROR - Error during xgboost optimization: No trials are completed yet.
2024-12-08 04:52:16,406 - ModelTrainer - ERROR - Traceback (most recent call last):
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 518, in train_models
    if study.best_trial is not None:
       ^^^^^^^^^^^^^^^^
  File "C:\Users\prite\Desktop\mlops-timeseries\.venv\Lib\site-packages\optuna\study\study.py", line 162, in best_trial
    best_trial = self._storage.get_best_trial(self._study_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prite\Desktop\mlops-timeseries\.venv\Lib\site-packages\optuna\storages\_in_memory.py", line 249, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.

2024-12-08 04:52:16,508 - ModelTrainer - ERROR - Error in xgboost training: XGBModel.fit() got an unexpected keyword argument 'eval_metric'
2024-12-08 04:52:16,509 - ModelTrainer - ERROR - Traceback (most recent call last):
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 518, in train_models
    if study.best_trial is not None:
       ^^^^^^^^^^^^^^^^
  File "C:\Users\prite\Desktop\mlops-timeseries\.venv\Lib\site-packages\optuna\study\study.py", line 162, in best_trial
    best_trial = self._storage.get_best_trial(self._study_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prite\Desktop\mlops-timeseries\.venv\Lib\site-packages\optuna\storages\_in_memory.py", line 249, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 347, in train_model_with_mapie
    model.fit(
  File "C:\Users\prite\Desktop\mlops-timeseries\.venv\Lib\site-packages\xgboost\core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
TypeError: XGBModel.fit() got an unexpected keyword argument 'eval_metric'

2024-12-08 04:52:16,510 - ModelTrainer - ERROR - Error in model training pipeline
2024-12-08 04:52:16,511 - ModelTrainer - ERROR - Traceback (most recent call last):
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 518, in train_models
    if study.best_trial is not None:
       ^^^^^^^^^^^^^^^^
  File "C:\Users\prite\Desktop\mlops-timeseries\.venv\Lib\site-packages\optuna\study\study.py", line 162, in best_trial
    best_trial = self._storage.get_best_trial(self._study_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prite\Desktop\mlops-timeseries\.venv\Lib\site-packages\optuna\storages\_in_memory.py", line 249, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 556, in train_models
    self.train_model_with_mapie(model_type, default_params[model_type].copy())
  File "C:\Users\prite\Desktop\mlops-timeseries\mlops_timeseries\models\trainer.py", line 347, in train_model_with_mapie
    model.fit(
  File "C:\Users\prite\Desktop\mlops-timeseries\.venv\Lib\site-packages\xgboost\core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
TypeError: XGBModel.fit() got an unexpected keyword argument 'eval_metric'

